name: LaraDumps Tests

on: ['push', 'pull_request']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-12, windows-latest]
        php: [ 8.2, 8.1 ]
        laravel: [ 10.*, 9.* ]
        dependency-version: [ prefer-stable ]
        include:
          - laravel: 10.*
            testbench: 8.*
          - laravel: 9.*
            testbench: 7.*
        exclude:
          - php: 8.0
            laravel: 10.*

    name: "PHP: ${{ matrix.php }} /  ${{ matrix.os }} / Lrvl: ${{ matrix.laravel }} (${{ matrix.dependency-version }})"
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          tools: composer:v2
          coverage: none

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: $(composer config cache-files-dir)
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
          restore-keys: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-

      - name: Install Composer dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction

      - name: Code Style 👨‍🏭
        run: composer cs-fixer
        if: runner.os == 'Linux'
        env:
          PHP_CS_FIXER_IGNORE_ENV: 1

      - name: Larastan ⚗️
        run: composer test:types
        if: matrix.laravel == '9.*' || matrix.laravel == '10.*'

      - name: Pest Tests 👨🏻‍🔬
        run: composer test:tests
